<?php
/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */
?>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }
    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
    tr:nth-child(even) {
        background-color: #dddddd;
    }
    .post-id{
        width:2%
    }
    .post-name{
        width:30%
    }

</style>

<div class="container">
    <div class="row text-center">
        <div class="col">
            <button id="add_joke_btn" type="button" class="btn btn-outline-primary">Add joke</button>
        </div>
    </div>
</div>
<table class="dinamic-tb">
    <tr>
        <th class="post-id">Icon Url</th>
        <th class="post-name">Url</th>
        <th class="post-name">Value</th>
        <th class="post-name"></th>
    </tr>
    <?php
    foreach ($block->getJokeCollection() as $key => $joke) {
        echo "<tr id='tr_{$joke->getJokeId()}'>
                    <td>" . $joke->getIconUrl() . "</td>
                    <td>" . $joke->getUrl() . "</td>
                    <td>" . $joke->getValue() . "</td>
                    <td>" . "<button onclick='dispatchDelete({$joke->getJokeId()})' type='button' class='btn btn-outline-primary' id='btn_{$joke->getJokeId()}'>Delete Joke</button>" . "</td>
                  </tr>";
    }
    ?>
</table>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script type="text/x-magento-init">
    {
    "#custom-form": {
    "validation": {}
    }
    }
</script>
<script  type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>jQuery.noConflict()</script>
<script type="text/javascript">

    let dispatchDelete = (jokeId) => {
        const url = "<?php echo $block->getJokeDeleteActionUrl() ?>?joke_id=" + jokeId;
        jQuery.ajax({
            url: url,
            type: "GET",
            dataType: "json",
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            },
            complete: (res) => {
                let data = res.responseJSON;
                if (data.status === 200) {
                    jQuery("#tr_" + jokeId).remove();
                }
                
            }
        });
    }

    //require(["jquery", 'jquery/ui'], function ($) {

    // Button
    jQuery("#add_joke_btn").click(() => {
        let url = "<?php echo $block->getJokeActionUrl() ?>";
        jQuery.ajax({
            url: url,
            type: "GET",
            dataType: "json",
            headers: {
                'X-Requested-With': 'XMLHttpRequest'
            },
            complete: (res) => {
                let data = res.responseJSON.data;
                console.log(data);
                jQuery('.dinamic-tb tr:last').after(`<tr><td>${data.icon_url}</td><td>${data.url}</td><td>${data.value}</td><td></td></tr>`);
            }
        });
    });

    //});
</script>

</body>
</html>